import SwiftUI
import UIKit
import Foundation

struct SettingsView: View {
    @ObservedObject var store: ProfileStore
    var profileID: UUID
    var isNewProfile: Bool = false
    var onCommit: ((VPNProfile, Bool) -> Void)? = nil
    var onAutodetectWDTTMtu: ((UUID) async throws -> Int)? = nil

    @Environment(\.dismiss) private var dismiss
    @State private var draft: VPNProfile?
    @State private var originalProfile: VPNProfile?
    @State private var showDeleteConfirmation = false
    @State private var showExportError = false
    @State private var exportErrorMessage = ""
    @State private var showQRScanner = false
    @State private var showScannerError = false
    @State private var scannerErrorMessage = ""
    @State private var showLinkGeneratedAlert = false
    @State private var showVKCallCreator = false
    @State private var vkCallCreatorStatus: String?

    private let wdttTunnelMTUPresets: [Int?] = [nil, 1280, 1320, 1360, 1380, 1400, 1420, 1440, 1500]

    private var profile: VPNProfile {
        draft ?? store.profiles.first(where: { $0.id == profileID }) ?? VPNProfile()
    }

    var body: some View {
        Form {
            Section(header: Text("Profile")) {
                TextField("Profile Name", text: binding(\.name))
                    .autocapitalization(.none)
                    .disableAutocorrection(true)

                Picker("Mode", selection: binding(\.transportMode)) {
                    ForEach(VPNTransportMode.allCases) { mode in
                        Text(mode.title).tag(mode)
                    }
                }
            }

            Section(header: Text("Proxy Settings")) {
                if profile.transportMode != .wdtt && profile.transportMode != .csqtt {
                    TextField("TURN Server URL", text: binding(\.vkLink))
                        .autocapitalization(.none)
                        .disableAutocorrection(true)
                }

                TextField("Peer Address (IP:Port)", text: binding(\.peerAddr))
                    .autocapitalization(.none)
                    .disableAutocorrection(true)

                if profile.transportMode != .wdtt && profile.transportMode != .csqtt {
                    TextField("Listen Address (IP:Port)", text: binding(\.listenAddr))
                        .autocapitalization(.none)
                        .disableAutocorrection(true)
                }

                Stepper("Connections (n): \(profile.nValue)", value: binding(\.nValue), in: 1...32)
                Stepper("Workers per TURN identity: \(profile.credsGroupSize)", value: binding(\.credsGroupSize), in: 1...32)
                Text("`n` controls total parallel TURN sessions. The vk-turn-proxy-ios runtime is tuned for fast 30-connection startup.")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }

            if profile.transportMode != .wdtt && profile.transportMode != .csqtt {
                Section(header: Text("WireGuard Config")) {
                    TextEditor(text: binding(\.wgQuickConfig))
                        .font(.system(.footnote, design: .monospaced))
                        .frame(minHeight: 150)
                        .autocapitalization(.none)
                        .disableAutocorrection(true)
                }
            }

            if profile.transportMode == .srtpCommunity {
                Section(header: Text("SRTP-Community")) {
                    TextField("WRAP Key Hex", text: binding(\.wrapKeyHex))
                        .font(.system(.footnote, design: .monospaced))
                        .autocapitalization(.none)
                        .disableAutocorrection(true)

                    Text("64 hex characters generated by the SRTP-WRAP server.")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
            }

            if profile.transportMode == .wdtt {
                Section(header: Text("WDTT")) {
                    TextField("VK Call URL or Hash", text: binding(\.vkLink))
                        .autocapitalization(.none)
                        .disableAutocorrection(true)

                    SecureField("WDTT Password", text: binding(\.wdttPassword))
                        .autocapitalization(.none)
                        .disableAutocorrection(true)

                    TextField("Primary VK Hash", text: binding(\.wdttClientKey))
                        .font(.system(.footnote, design: .monospaced))
                        .autocapitalization(.none)
                        .disableAutocorrection(true)

                    TextField("Extra VK Hashes", text: binding(\.wdttServerKey))
                        .font(.system(.footnote, design: .monospaced))
                        .autocapitalization(.none)
                        .disableAutocorrection(true)

                    Text("WireGuard settings are provisioned by the WDTT server after bootstrap.")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }

                Section {
                    Button {
                        vkCallCreatorStatus = nil
                        showVKCallCreator = true
                    } label: {
                        Label("Get VK Call URL", systemImage: "phone.badge.plus")
                    }

                    if let vkCallCreatorStatus, !vkCallCreatorStatus.isEmpty {
                        Text(vkCallCreatorStatus)
                            .font(.caption)
                            .foregroundColor(.secondary)
                    }

                    Text("Creates a new VK call from the VK account you confirm on the next screen and inserts its link at the top of this profile.")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }

                Section {
                    NavigationLink {
                        WDTTAdvancedSettingsView(
                            profile: bindingToDraftProfile(),
                            presets: wdttTunnelMTUPresets,
                            onAutodetectMTU: onAutodetectWDTTMtu.map { callback in
                                { try await callback(profileID) }
                            }
                        )
                    } label: {
                        Label("Advanced WDTT", systemImage: "slider.horizontal.3")
                    }
                }
            }

            if profile.transportMode == .csqtt {
                Section(header: Text("CSQTT")) {
                    SecureField("CSQTT Password", text: binding(\.csqttPassword))
                        .autocapitalization(.none)
                        .disableAutocorrection(true)

                    TextField("Web Port", value: binding(\.csqttWebPort), format: .number)
                        .keyboardType(.numberPad)

                    TextField("Client Tag", text: binding(\.csqttClientTag))
                        .autocapitalization(.none)
                        .disableAutocorrection(true)

                    Text("CSQTT runtime integration is not wired yet. These fields prepare the profile model for the upcoming client backend.")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
            }

            if profile.transportMode != .wdtt && profile.transportMode != .csqtt {
                Section(header: Text("Advanced Proxy")) {
                    Toggle(isOn: binding(\.useUdp)) {
                        VStack(alignment: .leading) {
                            Text("Use UDP")
                            Text("TCP is the stable default. Enable UDP only when the network requires it.")
                                .font(.caption)
                                .foregroundColor(.secondary)
                        }
                    }

                    TextField("TURN Host Override", text: binding(\.turnHost))
                        .autocapitalization(.none)
                        .disableAutocorrection(true)

                    TextField("TURN Port Override", text: binding(\.turnPort))
                        .keyboardType(.numberPad)
                        .autocapitalization(.none)
                        .disableAutocorrection(true)

                    Text("Leave host and port empty to use the server suggested by the invite link.")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
            }

            Section(header: Text("Transfer")) {
                Button(action: generateQuickImportLink) {
                    HStack {
                        Spacer()
                        Label("Generate Link", systemImage: "link.badge.plus")
                        Spacer()
                    }
                }
                .buttonStyle(.plain)
            }

            Section {
                Button(role: .destructive, action: {
                    showDeleteConfirmation = true
                }) {
                    HStack {
                        Spacer()
                        Text("Delete Profile")
                        Spacer()
                    }
                }
                .buttonStyle(.plain)
            }
        }
        .navigationTitle(isNewProfile ? "New Profile" : "Settings")
        .navigationBarTitleDisplayMode(.inline)
        .toolbar {
            ToolbarItemGroup(placement: .navigationBarTrailing) {
                Button(action: { showQRScanner = true }) {
                    Image(systemName: "qrcode.viewfinder")
                        .font(.title3)
                        .foregroundColor(.primary)
                }

                Button(action: { dismiss() }) {
                    Image(systemName: "checkmark.circle.fill")
                        .font(.title2)
                        .foregroundColor(.primary)
                }
            }
        }
        .onAppear {
            if draft == nil {
                draft = store.profiles.first(where: { $0.id == profileID })
            }
            if originalProfile == nil {
                originalProfile = store.profiles.first(where: { $0.id == profileID })
            }
        }
        .alert("Delete Profile?", isPresented: $showDeleteConfirmation) {
            Button("Delete", role: .destructive) {
                store.deleteProfile(profileID)
                dismiss()
            }
            Button("Cancel", role: .cancel) { }
        } message: {
            Text("Profile \"\(profile.name)\" will be permanently deleted.")
        }
        .alert("Export Error", isPresented: $showExportError) {
            Button("OK", role: .cancel) {}
        } message: {
            Text(exportErrorMessage)
        }
        .alert("Scanner Error", isPresented: $showScannerError) {
            Button("OK", role: .cancel) {}
        } message: {
            Text(scannerErrorMessage)
        }
        .alert("Link Copied", isPresented: $showLinkGeneratedAlert) {
            Button("OK", role: .cancel) {}
        } message: {
            Text("vbridge link copied to clipboard.")
        }
        .sheet(isPresented: $showQRScanner) {
            WireGuardQRScannerView(
                onCode: { code in
                    showQRScanner = false
                    applyScannedWireGuardConfig(code)
                },
                onError: { message in
                    showQRScanner = false
                    scannerErrorMessage = message
                    showScannerError = true
                }
            )
            .ignoresSafeArea()
        }
        .sheet(isPresented: $showVKCallCreator) {
            VKCallURLCreatorView(
                onSuccess: { link in
                    applyCreatedVKCallLink(link)
                },
                onCancel: {}
            )
        }
        .onDisappear {
            guard let draft else { return }
            let changed = originalProfile != draft
            if let idx = store.profiles.firstIndex(where: { $0.id == profileID }) {
                store.profiles[idx] = draft
                store.save()
            }
            onCommit?(draft, changed)
        }
    }

    private func applyScannedWireGuardConfig(_ raw: String) {
        let normalized = normalizeScannedText(raw)
        binding(\.wgQuickConfig).wrappedValue = normalized
    }

    private func normalizeScannedText(_ input: String) -> String {
        let trimmed = input.trimmingCharacters(in: .whitespacesAndNewlines)
        if let decoded = decodeAmneziaScannedText(trimmed) {
            return decoded
        }
        if trimmed.contains("\\n") && !trimmed.contains("\n") {
            return trimmed.replacingOccurrences(of: "\\n", with: "\n")
        }
        return trimmed
    }

    private func decodeAmneziaScannedText(_ input: String) -> String? {
        let normalized = input.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !normalized.isEmpty else { return nil }
        if normalized.contains("[Interface]") || normalized.contains("[Peer]") {
            return nil
        }

        for candidate in amneziaBase64Candidates(from: normalized) {
            guard let data = decodeBase64Payload(candidate) else { continue }
            if let config = extractWireGuardConfig(from: data) {
                return config
            }
        }
        return nil
    }

    private func amneziaBase64Candidates(from input: String) -> [String] {
        let raw = input.trimmingCharacters(in: .whitespacesAndNewlines)
        let compact = raw
            .replacingOccurrences(of: "\n", with: "")
            .replacingOccurrences(of: "\r", with: "")
            .replacingOccurrences(of: " ", with: "")

        let schemeSplitters = ["://", "wg://", "awg://", "amnezia://", "amneziawg://"]
        var candidates = [compact]

        for splitter in schemeSplitters {
            if let range = compact.range(of: splitter) {
                candidates.append(String(compact[range.upperBound...]))
            }
        }

        if let queryIndex = compact.firstIndex(of: "?") {
            candidates.append(String(compact[..<queryIndex]))
        }

        var uniqueCandidates: [String] = []
        for value in candidates {
            let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty, !uniqueCandidates.contains(trimmed) else { continue }
            uniqueCandidates.append(trimmed)
        }
        return uniqueCandidates
    }

    private func decodeBase64Payload(_ input: String) -> Data? {
        let sanitized = input
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")
        guard !sanitized.isEmpty else { return nil }

        let remainder = sanitized.count % 4
        let padded = remainder == 0 ? sanitized : sanitized + String(repeating: "=", count: 4 - remainder)
        return Data(base64Encoded: padded, options: [.ignoreUnknownCharacters])
    }

    private func extractWireGuardConfig(from data: Data) -> String? {
        let marker = Data("[Interface]".utf8)
        let peerMarker = Data("[Peer]".utf8)

        if let interfaceRange = data.range(of: marker) {
            let sliced = data[interfaceRange.lowerBound...]
            guard sliced.range(of: peerMarker) != nil,
                  let decoded = String(data: sliced, encoding: .utf8) ?? String(data: sliced, encoding: .ascii) else {
                return nil
            }
            return decoded.trimmingCharacters(in: .whitespacesAndNewlines)
        }

        if let decoded = String(data: data, encoding: .utf8) ?? String(data: data, encoding: .ascii),
           let range = decoded.range(of: "[Interface]") {
            let config = String(decoded[range.lowerBound...]).trimmingCharacters(in: .whitespacesAndNewlines)
            return config.contains("[Peer]") ? config : nil
        }

        return nil
    }

    private func generateQuickImportLink() {
        var payload: [String: Any] = [
            "name": profile.name,
            "mode": profile.transportMode.rawValue,
            "turn": profile.vkLink,
            "peer": profile.peerAddr,
            "listen": profile.listenAddr,
            "n": profile.nValue,
            "credsGroupSize": profile.credsGroupSize,
            "wg": profile.wgQuickConfig,
            "turnHost": profile.turnHost,
            "turnPort": profile.turnPort,
            "udp": profile.useUdp,
            "wrapKeyHex": profile.wrapKeyHex,
            "wdttPassword": profile.wdttPassword,
            "wdttClientKey": profile.wdttClientKey,
            "wdttServerKey": profile.wdttServerKey,
            "wdttFingerprint": profile.wdttFingerprint,
            "wdttClientIDMode": profile.wdttClientIDMode,
            "wdttUseVKCallsPreflight": profile.wdttUseVKCallsPreflight,
            "csqttPassword": profile.csqttPassword,
            "csqttClientTag": profile.csqttClientTag
        ]
        if let wdttTunnelMTU = profile.wdttTunnelMTU, wdttTunnelMTU > 0 {
            payload["wdttTunnelMTU"] = wdttTunnelMTU
        }
        if let csqttWebPort = profile.csqttWebPort, csqttWebPort > 0 {
            payload["csqttWebPort"] = csqttWebPort
        }

        guard JSONSerialization.isValidJSONObject(payload),
              let jsonData = try? JSONSerialization.data(withJSONObject: payload, options: []),
              let json = String(data: jsonData, encoding: .utf8) else {
            exportErrorMessage = "Failed to generate quick link."
            showExportError = true
            return
        }

        let base64 = Data(json.utf8).base64EncodedString()
        let link = "vbridge://\(base64)"
        UIPasteboard.general.string = link
        showLinkGeneratedAlert = true
    }

    private func applyCreatedVKCallLink(_ link: String) {
        let trimmedLink = link.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedLink.isEmpty else {
            vkCallCreatorStatus = "VK returned an empty call link."
            return
        }

        let existingLines = profile.vkLink
            .components(separatedBy: .newlines)
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty && $0 != trimmedLink }

        binding(\.vkLink).wrappedValue = ([trimmedLink] + existingLines).joined(separator: "\n")
        vkCallCreatorStatus = "Call created and added as the first link."
    }

    private func binding<T>(_ keyPath: WritableKeyPath<VPNProfile, T>) -> Binding<T> {
        Binding(
            get: { profile[keyPath: keyPath] },
            set: { newValue in
                if draft == nil {
                    draft = store.profiles.first(where: { $0.id == profileID })
                }
                draft?[keyPath: keyPath] = newValue
            }
        )
    }

    private func bindingToDraftProfile() -> Binding<VPNProfile> {
        Binding(
            get: { profile },
            set: { newValue in
                if draft == nil {
                    draft = store.profiles.first(where: { $0.id == profileID })
                }
                draft = newValue
            }
        )
    }

    private func mtuLabel(_ value: Int?) -> String {
        guard let value else { return "Auto (Server Suggested)" }
        return "\(value)"
    }
}

private struct WDTTAdvancedSettingsView: View {
    @Binding var profile: VPNProfile
    let presets: [Int?]
    var onAutodetectMTU: (() async throws -> Int)? = nil

    @State private var isDetectingMTU = false
    @State private var mtuStatusMessage: String?
    @State private var showMTUAlert = false
    @State private var mtuAlertTitle = ""
    @State private var mtuAlertMessage = ""

    var body: some View {
        Form {
            Section(header: Text("Runtime")) {
                Toggle(isOn: $profile.wdttUseVKCallsPreflight) {
                    VStack(alignment: .leading) {
                        Text("VK Calls Preflight")
                        Text("Disable only if you need the legacy captcha path instead of the VK Calls bootstrap path.")
                            .font(.caption)
                            .foregroundColor(.secondary)
                    }
                }

                Picker("Fingerprint", selection: $profile.wdttFingerprint) {
                    Text("Auto").tag("auto")
                    Text("Safari").tag("safari")
                    Text("Chrome").tag("chrome")
                }
                .pickerStyle(.menu)

                Picker("Client ID Filter", selection: $profile.wdttClientIDMode) {
                    Text("Default Rotation").tag("default")
                    Text("6287487").tag("6287487")
                    Text("8202606").tag("8202606")
                }
                .pickerStyle(.menu)
            }

            Section(header: Text("Tunnel MTU")) {
                Picker("Tunnel MTU", selection: $profile.wdttTunnelMTU) {
                    ForEach(presets, id: \.self) { mtu in
                        Text(mtuLabel(mtu)).tag(mtu as Int?)
                    }
                }
                .pickerStyle(.menu)

                if let mtuStatusMessage, !mtuStatusMessage.isEmpty {
                    Text(mtuStatusMessage)
                        .font(.caption)
                        .foregroundColor(.secondary)
                }

                Button {
                    guard !isDetectingMTU else { return }
                    Task {
                        await autodetectMTU()
                    }
                } label: {
                    HStack {
                        if isDetectingMTU {
                            ProgressView()
                                .progressViewStyle(.circular)
                        }
                        Text(isDetectingMTU ? "Detecting..." : "Autodetect MTU")
                    }
                }
                .disabled(isDetectingMTU || onAutodetectMTU == nil)

                VStack(alignment: .leading, spacing: 3) {
                    Text("Auto uses the MTU provisioned by the server.")
                    Text("1280: safest default for unstable mobile paths.")
                    Text("1360: balanced choice for most LTE and Wi-Fi networks.")
                    Text("1420: use on clean paths when you want lower overhead.")
                    Text("1500: only for LAN or very clean full-MTU routes.")
                }
                .font(.caption)
                .foregroundColor(.secondary)
            }
        }
        .navigationTitle("Advanced WDTT")
        .navigationBarTitleDisplayMode(.inline)
        .alert(mtuAlertTitle, isPresented: $showMTUAlert) {
            Button("OK", role: .cancel) {}
        } message: {
            Text(mtuAlertMessage)
        }
    }

    @MainActor
    private func autodetectMTU() async {
        guard let onAutodetectMTU else { return }
        isDetectingMTU = true
        mtuStatusMessage = "Testing MTU presets. The tunnel will reconnect several times."
        defer { isDetectingMTU = false }

        do {
            let detected = try await onAutodetectMTU()
            profile.wdttTunnelMTU = detected
            mtuStatusMessage = "Best MTU detected: \(detected)"
            mtuAlertTitle = "MTU Detected"
            mtuAlertMessage = "Best MTU: \(detected)"
            showMTUAlert = true
        } catch {
            mtuStatusMessage = "Autodetect failed: \(error.localizedDescription)"
            mtuAlertTitle = "Autodetect Failed"
            mtuAlertMessage = error.localizedDescription
            showMTUAlert = true
        }
    }

    private func mtuLabel(_ value: Int?) -> String {
        guard let value else { return "Auto (Server Suggested)" }
        return "\(value)"
    }
}
